---
name: Multi channel Network
version: '1.0'
client:
  organization: Org1MSP
channels:
  mychannel1:
    orderers:
    - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false
      peer0.org3.example.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false
  mychannel2:
    orderers:
    - orderer.example.com
    peers:
      peer1.org3.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org4.example.com:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false
organizations:
  Org1MSP:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/e8a13f1060fa565e60ca40ea4ee52edd79badc31ff95051833ac64ed68e9ea26_sk
    signedCert:
      path: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
  Org2MSP:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/fa27302ce44897687309ab8313169a31e2ca3f06a027b2fe2e28b7660ef08bcf_sk
    signedCert:
      path: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
  Org3MSP:
    mspid: Org3MSP
    peers:
    - peer0.org3.example.com
    - peer1.org3.example.com
    certificateAuthorities:
    - ca.org3.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/keystore/724c02c07e806d6761abffaaa3239beadc1313911d98fdc2bbb304f3426f393a_sk
    signedCert:
      path: crypto-config/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp/signcerts/Admin@org3.example.com-cert.pem
  Org4MSP:
    mspid: Org4MSP
    peers:
    - peer0.org4.example.com
    certificateAuthorities:
    - ca.org4.example.com
    adminPrivateKey:
      path: crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/keystore/c57be8e7437f126849ebe1918e626e8c77b8966f8b808d57cb93c16782948d55_sk
    signedCert:
      path: crypto-config/peerOrganizations/org4.example.com/users/Admin@org4.example.com/msp/signcerts/Admin@org4.example.com-cert.pem
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    eventUrl: grpcs://localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
  peer0.org2.example.com:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    grpcOptions:
      ssl-target-name-override: peer1.org3.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/tlscacerts/tlsca.org3.example.com-cert.pem
  peer0.org3.example.com:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer0.org3.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp/tlscacerts/tlsca.org3.example.com-cert.pem
  peer0.org4.example.com:
    url: grpcs://localhost:11051
    eventUrl: grpcs://localhost:11053
    grpcOptions:
      ssl-target-name-override: peer0.org4.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msptlscacerts/tlsca.org4.example.com-cert.pem
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.example.com
  ca.org2.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org2.example.com/ca/ca.org2.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
    caName: ca.org2.example.com
  ca.org3.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org3.example.com/ca/ca.org3.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
    caName: ca.org3.example.com
  ca.org4.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/org4.example.com/ca/ca.org4.example.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
    caName: ca.org4.example.com
